# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Ayesha Kaleem
title: Software Development Engineer
email: akaleem306@gmail.com
darkmode: false

# Social links
twitter_username: Ayesha546
github_username:  ayesha54
stackoverflow_username: "4784745"
linkedin_username: ayesha-kaleem-015187b0
xing_username: ayesha_kaleem


# Additional icon links
additional_links:
- title: Medium
  icon: fa-medium
  url: https://medium.com/@akaleem306
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  I am a young professional, graduated in **Computer Science** and having a year of working experience as a software research and development engineer at silicon valley’s startup named securiti.ai where I design and develop different small tools and microservices in Python and Golang, research about the cybersecurity and data protection regulatory compliances and frameworks such as CCPA and GDPR. 

  I have also worked with different programming languages, **front-end** technology stacks such as HTML, CSS, Bootstrap and javascript, **MVC** frameworks such as Laravel and Ruby on Rails in my whole internships and freelancing career. I am also familiar with the **DevOps** technologies such as Docker, Kubernetes and Ansible as I am always eager to learn and ready to take on new challenges and work with different technology stack. 


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Apart from professional information, I have been involved in different volunteering activities and have been a part of **The Citizen Organization** where I have volunteered in the Rahbar's Program for six weeks. I am a sports lover and love to play **Badminton** at Pakistan Sports Board, **Swimming** at Women Sports Complex and **Cycling** with GG Riders on every weekend. I am also really fond of **Traveling** and Hunza-Gilgit Baltistan is one of my favourite place to travel solo. I like to read books in my leisure time and stephen covey is one of my favourite writter.
  My ultimate goals are to become a good programmer and travel around the world. I also write technical blogs on **Medium** in my leisure time.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
